package io.appwrite.models

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types -l kotlin E:\Proyectos\Frondend\Android\Nuevos\Madriguera`.
 */

data class Role(
    val id: String,
    val description: String?
)