package io.appwrite.models

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types -l kotlin E:\Proyectos\Frondend\Android\Nuevos\Madriguera`.
 */

data class Room(
    val id: String,
    val name: String?,
    val precio: Float?,
    val description: String?,
    val photo: String?,
    val capacidad: Int?
)