package io.appwrite.models

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types -l kotlin E:\Proyectos\Frondend\Android\Nuevos\Madriguera`.
 */

data class UserAuth(
    val id: String,
    val name: String,
    val email: String?,
    val photoUrl: String?,
    val Role: String?,
    val phone: String?
)