package io.appwrite.models

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types -l kotlin E:\Proyectos\Frondend\Android\Nuevos\Madriguera`.
 */

data class Users(
    val uid: String,
    val email: String?,
    val phone: String?,
    val password: String,
    val displayName: String?,
    val photoUrl: String?,
    val role: String?
)